apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["sh", "-c", "date && sleep 10"]
      restartPolicy: Never
  backoffLimit: 3
